TARGETS = integralController playback power_gadget_whileloop triangleWave

all: $(TARGETS)

.PHONY: $(TARGETS)
integralController:
	$(MAKE) -C integralController all

playback:
	$(MAKE) -C playback all

power_gadget_whileloop:
	$(MAKE) -C power_gadget_whileloop all

triangleWave:
	$(MAKE) -C triangleWave all
